apiVersion: v1
kind: Namespace
metadata:
  name: tienda
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal
  namespace: tienda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portal
  template:
    metadata:
      labels:
        app: portal
    spec:
      containers:
        - name: portal
          image: nginx:1.27-alpine
          volumeMounts:
            - name: datos
              mountPath: /datos
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              memory: 64Mi
      volumes:
        - name: datos
          persistentVolumeClaim:
            claimName: datos-portal
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datos-portal
  namespace: tienda
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
